name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Show branch information
        run: |
          git branch -a
          git show-ref

      - name: Build and Deploy
        run: |
          cd /var/www/projects/quick_calendar
          npm install  # Install project dependencies
          npm run build  # Replace with your build command.
          cp -r ./build/* /var/www/html  # Assuming your web server root is /var/www/html
          sudo chown -R www-data:www-data /var/www/html  # Change ownership to the web server user.
          sudo chmod -R 755 /var/www/html  # Ensure the correct permissions.
